name: Release Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v1.0.0

permissions:
  contents: write # Needed for creating releases and uploading assets

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need all the tags for versioning

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          # Create directories
          mkdir -p bin
          
          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o bin/discovery-linux-amd64 ./cmd/discovery
          
          # Build for Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o bin/discovery-linux-arm64 ./cmd/discovery
          
          # Build for macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o bin/discovery-darwin-amd64 ./cmd/discovery
          
          # Build for macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o bin/discovery-darwin-arm64 ./cmd/discovery
          
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o bin/discovery-windows-amd64.exe ./cmd/discovery
          
          # Create compressed archives
          cd bin
          
          # Compress Linux binaries
          tar -czvf discovery-linux-amd64.tar.gz discovery-linux-amd64
          tar -czvf discovery-linux-arm64.tar.gz discovery-linux-arm64
          
          # Compress macOS binaries
          tar -czvf discovery-darwin-amd64.tar.gz discovery-darwin-amd64
          tar -czvf discovery-darwin-arm64.tar.gz discovery-darwin-arm64
          
          # Compress Windows binary
          zip -r discovery-windows-amd64.zip discovery-windows-amd64.exe

      - name: Generate checksum file
        run: |
          cd bin
          sha256sum *.tar.gz *.zip > SHA256SUMS.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            bin/discovery-linux-amd64.tar.gz
            bin/discovery-linux-arm64.tar.gz
            bin/discovery-darwin-amd64.tar.gz
            bin/discovery-darwin-arm64.tar.gz
            bin/discovery-windows-amd64.zip
            bin/SHA256SUMS.txt
